spring.application.name=pokemonv2

# Orígenes permitidos por CORS (coma-separados)
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Reducimos el ruido del startup de Spring
logging.level.root=INFO
logging.level.com.pokemon=INFO
